### ISSUE TITLE
[BUG] Hidden Item Conflicts

### ISSUE THREAD

**Issue by Zagna** [markmead/alpinejs-masonry#3]
I have a situation where I fetch the masonry items from a json file and use templates to render them.
```
<div x-data={items:[]} x-masonry x-init="fetch items">
  <template x-for="item in items">
    <div>
      <a :href="item.url">
        <div x-text="item.name"></div>
        <img :src="item.img">
        <p x-text="item.msg"></p>
      </a>
    </div>
  </template>
</div>
```
`<template>` stays in the `x-masonry` div and messes up with the layout.
Last column is above the others when the hidden element is first. Different results with where the hidden element is.
https://codepen.io/Zagna/pen/MWBNrJQ
In my case `<template>` was something that brought up this behavior but any hidden element causes this.

One fix could be in the `filter` to add an additional check for `display: none` or some other parameter?

**Comment by markmead** [comment]
Hmm, seems odd! Could you get an Alpine JS example, please?

**Comment by Zagna** [comment]
https://codepen.io/Zagna/pen/zYJOLqq
Here's the wall being built with `x-template`.

And I tried if `&& getComputedStyle(gridItem).display !== 'none'` would help.
https://codepen.io/Zagna/pen/ExeYpWN

**Comment by markmead** [comment]
I can't replicate this, so it isn't an issue with the package.

I think the issue is with your code, if you remove the `<div class="lorem">` it looks fine. Also, if you use `margin-bottom` instead of `padding-bottom` it looks fine.
