### ISSUE TITLE
[BUG] Issue with variable heights

### ISSUE THREAD

**Issue by binoclard** [markmead/alpinejs-masonry#4]
Hi,

Not sure if it is an intrinsic issue with your plugin, but I can not seem to make it work with elements more complex than simple images.

I am trying to use it with a bunch of "cards" (an article tag with other elements/div inside (img, title and a bit of text)), and the height is dictated by the height of the taller card. So I basically end up with a nice grid instead of a masonry :-)

I have tried to define the height to adapt to the content with `<article class="h-fit">`. It is better, but I have irregular gaps between "rows" and any screen resize makes it worse.

Any tips how to fix this would be really appreciated. I would love to be able to use it, as it is way simpler and cleaner than the "original Masonry".

Thanks in advance.

**Comment by binoclard** [comment]
Removing the shadow stuff seems to help a lot though.

**Comment by binoclard** [comment]
> ~Do you have an example? Screenshot or some code, thanks!~
> 
> Ignore me, I replicated it, you need to be using `align-items: flex-start` if using a `display: grid` - This is mentioned in the README. If that doesn't work, you can add either the `.poll` or `.delay` modifiers but they might not be needed.

I have flex-start on the main container. I'll go and try the `.poll` or `.delay` modifiers. Thanks.

**Comment by binoclard** [comment]
So the shadows seems to be the real culprit here: The `.delay` fixes it, but only if I delete the shadow and transitions classes.

**Comment by markmead** [comment]
What are the classes on the main container for the grid?

**Comment by binoclard** [comment]
```
<main class="container mx-auto">
    <section class="grid flex-start sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6"
      x-data
      x-masonry.wait.100>

        {{ Statamic stuff }}

    </section>
</main>
```

**Comment by binoclard** [comment]
> Example I tested with had a shadow and it was OK... Very odd, I'll try yours now.

Really…? I am trying to make it work with shadows for an hour without any improvement >__<

Thanks for your help!

**Comment by markmead** [comment]
It's `items-start` not `flex-start`.

**Comment by markmead** [comment]
Also, there's somethings wrong with your article card example:
- Missing closing `</div>`
- Unnecessary `mt-2` on the title
- Using `<h1>`, there should only be one on a page

**Comment by markmead** [comment]
No worries at all, I will update the README to make it more obvious.

Fair enough on the `mt-2` thing, I'd prefer to see `px-8 pb-8 pt-10` but that's just me. As for the `<h1>`, it's per page, not per `<article>` tag.
